mylist=[0,0,0,0,0]
metin1=input('String deger giriniz.')
sayi=int(input('İnteger deger giriniz.'))
ondalikli=float(input('float deger giriniz.'))
durum=bool((input('Boolean giriniz.')))
metin2=input('String deger giriniz.')
print('1. Deger={}'.format(metin1))
print(f'Türü={type(metin1)}')
print('2. Deger={}'.format(sayi))
print(f'Türü={type(sayi)}')
print('3. Deger={}'.format(ondalikli))
print(f'Türü={type(ondalikli)}')
print('4. Deger={}'.format(durum))
print(f'Türü={type(durum)}')
print('5. Deger={}'.format(metin2))
print(f'Türü={type(metin2)}')

